spring:
  context-path: /temis-server
  profiles.active: production
---
spring:
  profiles: local
  
  data:
   mongodb:
    uri: mongodb://localhost/temisdb
---
spring:
  profiles: production
    
  data:
   mongodb:
    uri: mongodb://temis_user:temisq1w2e3r4@ds013216.mlab.com:13216/temisdb
---

year.start.extract: 2013
url.laws: http://www.ceaam.net/sjc/legislacao/leis/
url.aldermen: http://www.camarasjc.sp.gov.br/vereadores/
path.leis: src/main/resources/data/html/